version: "3.4"

services:
  nexus:
    tty: true
    container_name: nexus-ram
    image: "sonatype/nexus3"
    restart: unless-stopped
    environment:
      - INSTALL4J_ADD_VM_PARAMS=-Xms1g -Xmx1g -XX:MaxDirectMemorySize=1g,
    ports:
      - "8081:8081"
    volumes:
      - nexus_data:/nexus-data
    networks:
      - jenkins-nexus

  jenkins:
    container_name: jenkins
    tty: true
    image: "jenkins/jenkins"
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "5000:5000"
    volumes:
      - jenkins_home:/var/jenkins_home
    depends_on:
      - nexus
    networks:
      - jenkins-nexus

volumes:
  jenkins_home:
    external: true
  nexus_data:
    external: true

networks:
  jenkins-nexus:
    driver: bridge
