version: "3.4"

services:
  nexus:
    tty: true
    container_name: nexus_compose
    image: "sonatype/nexus3"
    restart: unless-stopped
    environment:
      - INSTALL4J_ADD_VM_PARAMS=-Xms1g -Xmx1g -XX:MaxDirectMemorySize=1g,
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin,
      - container=oci,
      - SONATYPE_DIR=/opt/sonatype,
      - NEXUS_HOME=/opt/sonatype/nexus,
      - NEXUS_DATA=/nexus-data,
      - NEXUS_CONTEXT=,
      - SONATYPE_WORK=/opt/sonatype/sonatype-work,
      - DOCKER_TYPE=rh-docker
    ports:
      - "8182:8081"
    volumes:
      - nexus_data:/nexus-data
    networks:
      - jenkins-nexus

  jenkins:
    container_name: jenkins_compose
    tty: true
    image: "jenkins/jenkins"
    restart: unless-stopped
    ports:
      - "8181:8080"
      - "5001:5000"
    volumes:
      - jenkins_home:/var/jenkins_home
    depends_on:
      - nexus
    networks:
      - jenkins-nexus

volumes:
  jenkins_home:
    external: true
  nexus_data:
    external: true

networks:
  jenkins-nexus:
    driver: bridge
